default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  port: <%= ENV.fetch("DB_PORT") %>
development:
  <<: *default
  database: social_media_develoment
test:
  <<: *default
  database: social_media_test
production:
  <<: *default
  database: social_media_production
